lib/nidm_web/router.ex
defmodule NidmWeb.Router do
  use NidmWeb, :router
  import Phoenix.LiveView.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, { NidmWeb.LayoutView, :root }
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Nidm.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", NidmWeb do
    pipe_through :browser

    get "/welcome", SessionController, :new
    get "/unknown_user", ExitController, :unknown_user, as: :unknown
    #get "/exit", ExitController, :index

    resources "/session", SessionController, only: [:new, :create, :delete], singleton: true
    resources "/task1", RiskController
    resources "/exit", ExitController do
        get "/prolific", ExitController, :prolific, as: :prolific
    end

    get "/final_instructions", RiskController, :final_instructions

    live "/wait", WaitLive, layout: { NidmWeb.LayoutView, "root_no_header.html" }
    live "/pause", PauseLive, layout: { NidmWeb.LayoutView, "root_no_header.html" }
    live "/task2", GameLive, layout: { NidmWeb.LayoutView, "root_no_header.html" }
  end

  scope "/admin", NidmWeb do
    pipe_through :browser

    get "/export", DownloadController, :export
    get "/", AdminController, :index
    get "/bootstrap_test", AdminController, :bootstrap_test
    live "/dashboard", AdminLive, layout: { NidmWeb.LayoutView, "root_no_header.html" }
  end

  # Other scopes may use custom stacks.
  # scope "/api", NidmWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: NidmWeb.Telemetry
    end
  end
end

lib/nidm_web/controllers/exit_controller.ex
defmodule NidmWeb.ExitController do
    use NidmWeb, :controller

    alias Nidm.Users
    alias Nidm.Resources.ExitQuestion
    alias Nidm.ExitQuestions

    plug :logged_in_user when action in [:index]
    plug :put_root_layout, "root_no_header.html"
    plug :put_layout, "regular.html"

    def action(conn, _) do
        user_id = Map.get(conn.assigns, :user_id, nil)
        apply(__MODULE__, action_name(conn),
            [conn, conn.params, Users.get_user(user_id)])
    end

    def unknown_user(conn, _params, current_user) do
        render conn, :unknown, %{ user: current_user }
    end

    def prolific(conn, _params, current_user) do
        old_status = current_user.status
        current_user = Users.set_status(current_user, "exit")
        render(conn, :prolific, %{ user: current_user, old_status: old_status })
    end

    def index(conn, _params, current_user) do
        case current_user.status == "flushed" do
            true ->
                redirect(conn, to: "/exit/#{current_user.id}/prolific")
            false ->
                questions = ExitQuestions.get_by_user_id(current_user.id)
                questions = case questions == nil do
                    true ->
                        { :ok, questions } = ExitQuestions.create_exit_question(%{ user_id: current_user.id })
                        questions
                    false -> questions
                end
                changeset = ExitQuestion.exit_question_changeset(questions, %{})
                render(conn, :index, %{
                    user: current_user,
                    changeset: changeset,
                    questions: questions
                })
        end
    end

    def update(conn, %{ "id" => id, "exit_question" => params }, current_user) do
        question = ExitQuestions.get_exit_question(id)

        question
        |> ExitQuestion.exit_question_changeset(params)
        |> Nidm.Repo.update()
        |> case do
            { :ok, _ } ->
                redirect(conn, to: "/exit/#{current_user.id}/prolific")
            { :error, %Ecto.Changeset{} = changeset } ->
                render(conn, "index.html", %{
                    user: current_user,
                    changeset: changeset,
                    questions: question
                })
        end

    end



end

lib/nidm_web/views/exit_view.ex
defmodule NidmWeb.ExitView do
    use NidmWeb, :view
end

lib/nidm_web/templates/exit/index.html.eex
<header class="nidm"></header>

<%= if @user do %>

    <div class="body">

    <section class="phx-hero exit">
        <h1>Questionnaire</h1>
    </section>

    <%= form_for @changeset, Routes.exit_path(@conn, :update, @questions), fn f -> %>
    
        <fieldset class="exit">
            <p>1. What is your age?</p>
            <%= select f, :q_age, 18..100 %>
            <%= error_tag f, :q_age %>
        </fieldset>

        <fieldset class="exit">
            <p>2. What is your gender?</p>
            <span class="radio"><%= radio_button f, :q_gender, 1 %><label>female</label></span>
            <span class="radio"><%= radio_button f, :q_gender, 2 %><label>male</label></span>
            <span class="radio"><%= radio_button f, :q_gender, 3 %><label>other</label></span>
            <%= error_tag f, :q_gender %>
        </fieldset>

        <fieldset class="exit">
            <p>3. What is your mother tongue?</p>
            <span class="radio"><%= radio_button f, :q_mtongue, 1 %><label>English</label></span>
            <span class="radio"><%= radio_button f, :q_mtongue, 2 %><label>other</label></span>
            <%= error_tag f, :q_mtongue %>
        </fieldset>

        <fieldset class="exit">
            <p>4. What is your highest completed level of education?</p>
            <span class="radio"><%= radio_button f, :q_edu, 1 %><label>No formal education</label></span>
            <span class="radio"><%= radio_button f, :q_edu, 2 %><label>Primary school (elementary education)</label></span>
            <span class="radio"><%= radio_button f, :q_edu, 3 %><label>Lower secondary (secondary completed does not allow entry to university: obligatory school)</label></span>
            <span class="radio"><%= radio_button f, :q_edu, 4 %><label>Upper secondary (programs that allows entry to university)</label></span>
            <span class="radio"><%= radio_button f, :q_edu, 5 %><label>Post secondary, non-tertiary (other upper secondary programs toward labor market or technical formation)</label></span>
            <span class="radio"><%= radio_button f, :q_edu, 6 %><label>Lower level tertiary, first stage (also technical schools at a tertiary level)</label></span>
            <span class="radio"><%= radio_button f, :q_edu, 7 %><label>Upper level tertiary (Master, Doctor)</label></span>
            <span class="radio"><%= radio_button f, :q_edu, 8 %><label>No answer</label></span>
            <%= error_tag f, :q_edu %>
        </fieldset>

        <fieldset class="exit">
            <p>5. What is your country of residence?</p>
            <%
                countries = Enum.sort(Countries.all, &(&1.name < &2.name))
                options = Enum.map(countries, &{&1.name, &1.country_code})
            %>
            <%= select f, :q_residence, options, prompt: "-- Please select --" %>
            <%= error_tag f, :q_residence %>
        </fieldset>

        <fieldset class="exit">
            <p>6. How concerned were/are you to attract COVID-19?</p>
            <span class="radio"><%= radio_button f, :q_c19_concern, 1 %><label>very</label></span>
            <span class="radio"><%= radio_button f, :q_c19_concern, 2 %><label>a bit</label></span>
            <span class="radio"><%= radio_button f, :q_c19_concern, 3 %><label>hardly</label></span>
            <span class="radio"><%= radio_button f, :q_c19_concern, 4 %><label>not at all</label></span>
            <%= error_tag f, :q_c19_concern %>
        </fieldset>

        <fieldset class="exit">
            <p>7. Did you get COVID-19?</p>
            <span class="radio"><%= radio_button f, :q_c19_positive, 1 %><label>yes</label></span>
            <span class="radio"><%= radio_button f, :q_c19_positive, 0 %><label>no</label></span>
            <%= error_tag f, :q_c19_positive %>
        </fieldset>

        <fieldset class="exit">
            <p>8. Remarks</p>
            <%= textarea(f, :q_remarks) %>
        </fieldset>

        <fieldset>
            <%= submit "Submit", class: "button" %>
        </fieldset>
    <% end %>


    </div>

<% end %>

lib/nidm_web/templates/exit/prolific.html.eex
<header class="nidm"></header>

<%= if @user do %>

    <%
        pounds = Float.round(((@user.earned_points || 0) / 500), 2)
        euros = Float.round(pounds * 1.17, 2)
    %>

    <div class="body">
        <section class="phx-hero exit">
            <h1>Thank you</h1>
            <%= if @old_status == "flushed" do %>
                <p>Dear participant,</p>

                <p class="left-align">thank you for participating in the academic study 
                “Progression of epidemics in a networking game”! As 
                explained in the instructions, participants are assigned 
                to groups. This means that when not enough people show 
                up to form a group of 60, not everybody gets to 
                participate.</p>
                <p class="left-align">Unfortunately, you could not be assigned to a group.</p>
                <p class="left-align">The minimum payment as announced in the study will be 
                transferred to you shortly. Please make sure to 
                exit the study by clicking the “Back to Prolific” button 
                below.</p>

            <% else %>

                <p>Dear participant,</p>

                <p class="left-align">thank you for participating in the academic study 
                “Progression of epidemics in a networking game”! Your final 
                score is <%= @user.earned_points %>. Your payment will be processed 
                and transferred to you shortly. Please make sure to exit the study 
                by clicking the “Back to Prolific” button below.</p>

            <% end %>

            <p>Kind regards,</p>
            <p>Hendrik Nunner</p>

            <p><a href="<%= @user.redirect_url %>" class="button">
            Back to Prolific</a></p>

        </section>
    </div>

<% end %>

lib/nidm_web/templates/exit/unknown.html.eex
<header class="nidm"></header>

<div class="body">

    <%= if @user do %>

    <section class="phx-hero exit">
        <h1>Your access token isn't recognized</h1>
    </section>
    
    <% else %>

    <section class="phx-hero exit">
        <h1>Your user account isn't recognized</h1>
    </section>

    <% end %>

</div>