lib/nidm_web/router.ex
defmodule NidmWeb.Router do
  use NidmWeb, :router
  import Phoenix.LiveView.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, { NidmWeb.LayoutView, :root }
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Nidm.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", NidmWeb do
    pipe_through :browser

    get "/welcome", SessionController, :new
    get "/unknown_user", ExitController, :unknown_user, as: :unknown
    #get "/exit", ExitController, :index

    resources "/session", SessionController, only: [:new, :create, :delete], singleton: true
    resources "/task1", RiskController
    resources "/exit", ExitController do
        get "/prolific", ExitController, :prolific, as: :prolific
    end

    get "/final_instructions", RiskController, :final_instructions

    live "/wait", WaitLive, layout: { NidmWeb.LayoutView, "root_no_header.html" }
    live "/pause", PauseLive, layout: { NidmWeb.LayoutView, "root_no_header.html" }
    live "/task2", GameLive, layout: { NidmWeb.LayoutView, "root_no_header.html" }
  end

  scope "/admin", NidmWeb do
    pipe_through :browser

    get "/export", DownloadController, :export
    get "/", AdminController, :index
    get "/bootstrap_test", AdminController, :bootstrap_test
    live "/dashboard", AdminLive, layout: { NidmWeb.LayoutView, "root_no_header.html" }
  end

  # Other scopes may use custom stacks.
  # scope "/api", NidmWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: NidmWeb.Telemetry
    end
  end
end

lib/nidm_web/controllers/session_controller.ex
defmodule NidmWeb.SessionController do

    use NidmWeb, :controller

    alias Nidm.{ Users, Networks }
    alias Nidm.Resources.User

    require Logger

    plug :put_root_layout, "root_no_header.html"
    plug :put_layout, "regular.html"
    plug :redirect_if_necessary

    def new(conn, params) do
        # make sure params keys are downcased
        params = Enum.reduce params, %{}, fn { key, value }, acc ->
            Map.put(acc, String.downcase(key), value)
        end
        # search user by prolific_pid
        user = case Enum.member?(Map.keys(params), "prolific_pid") do
            true -> Users.get_user_by_prolific_pid(params["prolific_pid"])
            false -> Users.get_user_by_access_token(params["access_token"])
        end

        # check if we have a user found by access token, if not redirect to unknown user
        case user do
            %User{} ->
                # does it make sense to let this guy follow through, are
                # there any available networks?
                signin_changeset = User.signin_changeset(user)
                # render welcome page
                render conn, :new, %{ user: user, signin_changeset: signin_changeset }
            _ ->
                conn
                |> put_flash(:error, "The provided access token is not associated with a user account")
                |> redirect(to: "/unknown_user")
        end
    end


    def create(conn, %{ "user" => params }) do
        # get id
        %{ "id" => id } = params
        # get user
        user = Users.get_user(id)
        # if there is a user continue to task_1, otherwise exit
        case user do
            %User{} ->
                status = infer_user_status(user)
                # update status
                params = Map.put(params, "status", status)
                # create changeset
                signin_changeset = User.signin_changeset(user, params)
                # update User
                updated_user = Users.update(user, signin_changeset)
                # if a changeset is returned, then something is wrong
                case updated_user do
                    %Ecto.Changeset{} ->
                        conn
                        |> put_flash(:error, "Please agree to our terms of service.")
                        |> render(:new, %{ user: user, signin_changeset: updated_user })
                    _ ->
                        redirect_path = case updated_user.status do
                            "signed_in" -> "/task1"
                            "assessment" -> "/task1"
                            "flushed" -> "/exit"
                            "exit_questions" -> "/exit"
                            "exit" -> "/exit"
                            "waiting" -> "/wait"
                            "game" -> "/task2"
                            "question_1" -> "/task1"
                            "question_2" -> "/task1"
                            "question_3" -> "/task1"
                            "question_4" -> "/task1"
                            "question_5" -> "/task1"
                            "final_instructions" -> "/final_instructions"
                        end
                        conn
                        |> login(updated_user)
                        |> redirect(to: redirect_path)
                end
            _ ->
                conn
                |> put_flash(:error, "The ID of the user account could not be found")
                |> redirect(to: "/unknown_user")
        end
    end


    defp infer_user_status(user) do
        case user.status == nil do
            true ->
                # no status
                available_networks = Networks.available_networks()
                case Enum.empty?(available_networks) do
                    true -> "flushed"
                    false -> "signed_in"
                end
            false ->
                # keep status
                user.status
        end
    end


    defp redirect_if_necessary(conn, _params) do
        # if logged in redirect
        conn
    end


    defp login(conn, user) do
        conn = conn
        |> put_session(:user_id, user.id)
        conn
    end



end

lib/nidm_web/views/session_view.ex
defmodule NidmWeb.SessionView do
    use NidmWeb, :view
end

lib/nidm_web/templates/session/new.html.eex
<header class="nidm"></header>

<div class="body">

    <section class="phx-hero">
    <h1>Welcome</h1>
    </section>

    <section class="welcome">
        <h2>Instructions</h2>

        <p>You are now taking part in a decision-making experiment. Please 
        read the following instructions carefully. They contain everything 
        you need to know to participate in the experiment. The data for 
        this study is collected and controlled by Hendrik Nunner of the 
        Utrecht University Institute (EUI). If you have any questions, 
        please email Hendrik Nunner at
        <a href="mailto:h.nunner@uu.nl">h.nunner@uu.nl</a>.</p>

        <p>During the experiment, you can earn points. These points will be converted 
        at the end of the experiment at the exchange rate of:</p>
        <p class="center"><strong>500 points = £1.00</strong></p>
        <p>The number of points you earn depends on your own choices and the choices 
        of other participants. Depending on your performance in the experiment, you 
        will earn maximally £10.00. We will guarantee you a minimum payment 
        of £5.00 per 60 minutes of your participation as required by Prolific, 
        but if your earned points are beyond the minimum payment, you get the 
        difference as your bonus. For example, if you earn 3000 points and the 
        experiment takes 60 minutes, you earn £6.00: £5.00 for the minimum payment 
        and £1.00 in addition as a bonus. The experiment will take a maximum of 100 
        minutes (1 hour 40 minutes), probably less. It may happen that you cannot be 
        assigned to a group to participate in the study. In that case, you will 
        receive the minimum amount as announced on Prolific.</p>

        <p>At the end of the experiment, you will be shown a message 
        confirming your participation and a link redirecting you to 
        Prolific when clicked on. Clicking this link is required to 
        finalize your participation. Only when you completed all tasks 
        and got redirected to Prolific, you will receive the money you 
        earned during the experiment in your Prolific account.</p>

        <p>Please note that you may at all times quit the study without 
        any explanation or consequences.</p>

        <%= form_for @signin_changeset, Routes.session_path(@conn, :create), [method: :post, as: :user], fn f -> %>

            <%= hidden_input f, :id, value: @user.id %>
            <%= hidden_input f, :agreed_personal_data, value: true %>
            <%= hidden_input f, :agreed_terms, value: true %>

            <p>Please click “continue” to proceed with the instructions.</p>

            <p>
                <%= submit "Continue", type: "submit", id: "go" %>
            </p>

        <% end %>

    </section>

</div>